import {useMemo,useState} from "react";
import Link from "next/link";
import Layout from "../components/Layout";
const albumNames=["Семейные моменты","Милена","Даниил","Путешествия","Праздники","Школа и достижения","Не разбирать"];
const tips=[["01","Загрузить","Выбери фотографии с телефона. Они останутся только в памяти этой вкладки."],["02","Отобрать","Отметь семейные снимки, исключи случайные и личные."],["03","Разложить","Выбери альбом для каждого снимка. Сохранение в облако появится позже."]];
export default function FamilyPhotos(){
 const [photos,setPhotos]=useState([]),[filter,setFilter]=useState("Все"),[frequency,setFrequency]=useState("Каждую неделю");
 const selected=useMemo(()=>photos.filter(p=>filter==="Все"||p.album===filter),[photos,filter]);
 function addFiles(files){if(!files)return;const arr=Array.from(files).filter(f=>f.type.startsWith("image/")).slice(0,60);setPhotos(prev=>[...prev,...arr.map((file,i)=>({id:Date.now()+"-"+i+"-"+Math.random(),name:file.name,url:URL.createObjectURL(file),album:"На проверку",approved:false}))].slice(0,120))}
 function change(id,patch){setPhotos(prev=>prev.map(p=>p.id===id?{...p,...patch}:p))}
 function remove(id){setPhotos(prev=>{const item=prev.find(p=>p.id===id);if(item)URL.revokeObjectURL(item.url);return prev.filter(p=>p.id!==id)})}
 return <Layout active="/family"><div className="fp"><Link href="/family" className="back">← Моя семья</Link><div className="eyebrow">FAMILY COMPANION · ЛИЧНЫЙ РАЗДЕЛ</div><h1>Семейный <em>фотоархив</em></h1><p className="lead">Тёплые воспоминания, которые не потеряются среди тысяч снимков. Начинаем с безопасного ручного отбора — без доступа к чужим телефонам и без автоматической публикации.</p>
 <div className="notice"><strong>Демонстрация без облачного хранения</strong><p>Здесь можно выбрать, просмотреть и рассортировать фото в текущей вкладке. Файлы не отправляются на сервер и исчезнут из интерфейса при обновлении страницы. Это ещё не резервная копия — оригиналы на телефоне не удаляй.</p></div>
 <div className="steps">{tips.map(([n,t,d])=><div className="step" key={n}><span>{n}</span><strong>{t}</strong><p>{d}</p></div>)}</div>
 <section className="panel"><div className="heading"><div><div className="eyebrow">НОВЫЕ СНИМКИ</div><h2>Разобрать фотографии</h2></div><label className="upload">＋ Выбрать фото<input type="file" accept="image/*" multiple onChange={e=>{addFiles(e.target.files);e.target.value=""}}/></label></div>
 <div className="filters">{["Все","На проверку",...albumNames].map(a=><button className={filter===a?"active":""} key={a} onClick={()=>setFilter(a)}>{a} {a==="Все"?photos.length:photos.filter(p=>p.album===a).length}</button>)}</div>
 {selected.length?<div className="gallery">{selected.map(p=><article key={p.id}><img src={p.url} alt={p.name}/><div className="photoMeta"><small title={p.name}>{p.name}</small><label>Альбом<select value={p.album} onChange={e=>change(p.id,{album:e.target.value,approved:false})}><option>На проверку</option>{albumNames.map(a=><option key={a}>{a}</option>)}</select></label><div className="controls"><button disabled={p.album==="На проверку"||p.album==="Не разбирать"} onClick={()=>change(p.id,{approved:!p.approved})}>{p.approved?"✓ Отобрано":"Подтвердить"}</button><button onClick={()=>remove(p.id)}>Убрать из просмотра</button></div></div></article>)}</div>:<div className="empty"><span>▧</span><h3>Здесь появятся семейные моменты</h3><p>Выбери несколько фотографий и попробуй распределить их по альбомам. Ничего с телефона не удаляется.</p></div>}
 </section><section className="panel"><div className="eyebrow">БУДУЩАЯ АВТОМАТИЗАЦИЯ</div><h2>Плановый разбор</h2><p>Частоту можно выбрать для будущей настройки. Автоматическая синхронизация и напоминания пока не включены.</p><div className="freq">{["Каждую неделю","Раз в две недели"].map(x=><button key={x} className={frequency===x?"active":""} onClick={()=>setFrequency(x)}>{x}</button>)}</div><p className="muted">Выбранный вариант: {frequency}. Для настоящего расписания понадобятся отдельное разрешение на каждом телефоне, приватное хранилище и семейные правила доступа.</p></section>
 <section className="panel"><div className="eyebrow">ДОРОЖНАЯ КАРТА</div><h2>Что подключим дальше</h2><div className="road"><div><b>01 · Защищённый архив</b><p>Приватное облако, резервные копии и восстановление, раздельные права доступа.</p></div><div><b>02 · Телефоны семьи</b><p>Подключение каждого устройства только с согласия владельца; для детских — с разрешения родителей.</p></div><div><b>03 · Умный отбор</b><p>Предложения по событиям и семейным кадрам с подтверждением человеком, без распознавания лиц по умолчанию.</p></div><div><b>04 · Фотоистории</b><p>Автоматически оформленные альбомы, хронология, подборки к праздникам.</p></div></div></section></div>
 <style jsx>{`.fp{max-width:1180px;margin:auto}.back{color:#d9bf78;font-size:13px}.eyebrow{color:#c9a850;letter-spacing:.2em;font-size:10px;margin:20px 0 12px}.fp h1{font:clamp(43px,6vw,76px) Georgia,serif;margin:0 0 20px}.fp h1 em{color:#d6bb72}.lead{max-width:790px;color:#bcb6a9;line-height:1.8}.notice{background:#172126;border:1px solid #56747b66;padding:20px;border-radius:17px;margin:28px 0}.notice strong{color:#b9e0e2}.notice p,.panel p,.step p{color:#aaa69d;font-size:13px;line-height:1.7}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.step{padding:22px;background:#171819;border:1px solid #bfa25c33;border-radius:17px}.step span{color:#d2b36d;margin-right:12px}.step strong{font-size:17px}.panel{margin-top:26px;padding:25px;background:#151617;border:1px solid #bfa25c33;border-radius:19px}.panel h2{font:31px Georgia,serif;margin:0 0 15px}.heading{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.upload{cursor:pointer;display:inline-block;border-radius:12px;padding:15px 23px;color:#18140c;background:linear-gradient(110deg,#d4ad57,#f6dc96,#b58a36);font-weight:700}.upload input{display:none}.filters,.freq{display:flex;gap:9px;flex-wrap:wrap;margin:20px 0}.filters button,.freq button,.controls button{border:1px solid #bfa25c44;border-radius:10px;background:#242525;color:#ddd3bd;padding:9px 12px;cursor:pointer}.filters button.active,.freq button.active{background:#675229;color:#fff2ce}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.gallery article{overflow:hidden;border:1px solid #bfa25c33;border-radius:15px;background:#1e2021}.gallery img{width:100%;height:200px;object-fit:cover;display:block}.photoMeta{padding:15px}.photoMeta small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#a9a49a}.photoMeta label{display:block;font-size:12px;margin-top:12px}.photoMeta select{display:block;margin-top:7px;width:100%;background:#111;color:white;border:1px solid #bfa25c55;border-radius:8px;padding:10px}.controls{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.controls button{font-size:11px}.controls button:disabled{opacity:.35;cursor:not-allowed}.empty{text-align:center;padding:45px 20px;color:#aaa}.empty span{font-size:58px;color:#d2b36d}.empty h3{font:26px Georgia,serif;color:#e5d7b6}.muted{font-size:12px!important}.road{display:grid;grid-template-columns:1fr 1fr;gap:12px}.road div{border-left:2px solid #bfa25c;padding:12px 18px;background:#ffffff06}.road b{color:#ecd497}@media(max-width:800px){.steps,.gallery{grid-template-columns:1fr 1fr}}@media(max-width:580px){.steps,.gallery,.road{grid-template-columns:1fr}.panel{padding:18px}.gallery img{height:240px}}`}</style></Layout>
}